### ISSUE TITLE
Make slimmage support "height"

### ISSUE THREAD

**Issue by perosb** [imazen/slimmage#3]
Have any thoughts been given to make slimmage support height?

For example if I have an image which in html with querystrings will be:
  src=myImage.jpg?width=500&height=200

slimmage will change width=320 but keep height, whereas it might want to change height to 128

**Comment by nathanaeljones** [comment]
First draft of 'height' and 'zoom' support just landed in `unstable` branch. This made slimmage.js 30% bigger. It even increased the minified+gzip size of slimmage.js **20% from 1.76kb to 2.12kb**.

https://github.com/imazen/slimmage/tree/unstable

We now have CI and automated tests (help cleaning them up would be great!). 

Our automated tests from the last API call - click to browse.
[![Selenium Test Status](https://saucelabs.com/browser-matrix/imazen.svg)](https://saucelabs.com/u/imazen)

Some of our test failures are due to uneven selenium command support. 

* We can't run our window resizing tests on android; they need to be turned off for that platform: https://saucelabs.com/tests/1e159b5b5e80428798360256991267b9
* We're trying to run our non-ie-compatible syntax tests on IE 6 and 7: https://saucelabs.com/tests/761eb47116174d588b4cb8b6f96416ec
* We're getting a bad gateway error on IE. 

I suck at automated testing of front-end components, but this is the only path that doesn't end in insanity.

**Comment by nathanaeljones** [comment]
I'm closing this as fixed for now; unstable will be moving to master soon. Let us know if the unstable branch fails to meet an expectations re: height.
