### ISSUE TITLE
Sometimes the WebP test hasn't completed before slimming has finished

### ISSUE THREAD

**Issue by Jeavon** [imazen/slimmage#39]
You can refresh a page and one time jpgs remain and refresh again and this time webp images are there etc...
I've tried and failed to find a reason or pattern to this....

**Comment by nathanaeljones** [comment]
It's by design. The WebP test can be extremely slow, and is unpredictable. We don't wait for it, instead, we accept the race condition and that we may end up falling back to jpeg. 

It's strange that there is a mix of both, though, as I'd expect to see either all jpeg or all web; the source URLs should be set within 5ms of each other. Is slimmage the last script element instead of the first?

**Comment by Jeavon** [comment]
Ah ok, might it be possible to have a setting to wait for the webp test as it would be good to be able to avoid having the images sometimes loaded both in jpg and webp if the user visits the page twice..?

I've tried positioning the slimmage js in all different positions but it didn't make any difference... I find it very easy to replicate just by  refreshing the same page and monitoring in network tools.

**Comment by Jeavon** [comment]
Just did a test on a page where 11 images are being slimmed, out of 18 refreshes, webp was requested on only 2 of them.

**Comment by nathanaeljones** [comment]
I was able to reproduce this in the integration tests, and resolved it by adding `webpTimeout`. 50 milliseconds seems to do it. 

See https://github.com/imazen/slimmage/tree/unstable#configuration-reference---windowslimmage-object

Now, if I can just get the IE 6, 8 & 9 tests to test properly, I can release this.

**Comment by Jeavon** [comment]
That's fantastic! Good luck with the IE tests, the whole test lab you have setup is amazing!
